<!--
**r5254/r5254** is a ✨ _special_ ✨ repository because its `README.md` (this file) appears on your GitHub profile.

Here are some ideas to get you started:

- 🔭 I’m currently working on ...
- 🌱 I’m currently learning ...
- 👯 I’m looking to collaborate on ...
- 🤔 I’m looking for help with ...
- 💬 Ask me about ...
- 📫 How to reach me: ...
- 😄 Pronouns: ...
- ⚡ Fun fact: ...
-->
### Hi there 👋
# 안녕하세요
## 만나서 반가와요:wink:
> - [x] 이메일 : mschakim@gmail.com
> - [x] 모바일 : 010-8653-9040

🔭 열공중입니다
